Numpy examples

Given are 2 similar dimensional numpy arrays, how to get a numpy array output in which every element is an element-wise sum of the 2 numpy arrays?

In [ ]:
import numpy as np

print(np.__version__)

In [ ]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[10,11,12],
              [13,14,15]])

c = a + b

print(c)

Given a numpy array (matrix), how to get a numpy array output which is equal to the original matrix multiplied by a scalar?



In [ ]:
a = np.array([[1,2,3],
              [4,5,6]])

b = 2*a # multiplying the numpy array a(matrix) by 2

print(b)

Create an identity matrix of dimension 4-by-4

In [ ]:
i = np.eye(4)

print(i)

Convert a 1-D array to a 3-D array

This code generates a list of numbers from 0 t0 26. then afterwards  it is then reshaped into a 3-d array .

In [ ]:
a = np.array([x for x in range(27)])

o = a.reshape((3,3,3))

print(o)

Convert all the elements of a numpy array from float to integer datatype

In [ ]:
a = np.array([[2.5, 3.8, 1.5],
              [4.7, 2.9, 1.56]])

o = a.astype('int')

print(o)

Convert a binary numpy array (containing only 0s and 1s) to a boolean numpy array

In [ ]:

a = np.array([[1, 0, 0],
              [1, 1, 1],
              [0, 0, 0]])

o = a.astype('bool')

print(o)

Stack 2 numpy arrays horizontally i.e., 2 arrays having the same 1st dimension (number of rows in 2D arrays)

In [ ]:
a1 = np.array([[1,2,3],
               [4,5,6]])

a2 = np.array([[7,8,9],
               [10,11,12]])

o = np.hstack((a1, a2))

print(o)

Stack 2 numpy arrays vertically i.e., 2 arrays having the same last dimension (number of columns in 2D arrays)

In [ ]:
a1 = np.array([[1,2],
               [3,4],
               [5,6]])

a2 = np.array([[7,8],
               [9,10],
               [10,11]])

o = np.vstack((a1, a2))

print(o)

Generate a sequence of numbers in the form of a numpy array from 0 to 100 with gaps of 2 numbers, for example: 0, 2, 4 ....

In [ ]:
import numpy as np
list_of_numbers = [x for x in range(0, 101, 2)]

o = np.array(list_of_numbers)

print(o)

#OR#

o = np.arange(0, 101, 2)

print(o)

From 2 numpy arrays, extract the indexes in which the elements in the 2 arrays match

In [ ]:
a = np.array([1,2,3,4,5])

b = np.array([1,3,2,4,5])

print(np.where(a == b))

Output a sequence of equally gapped 5 numbers in the range 0 to 100 (both inclusive)

In [ ]:
o = np.linspace(0, 100, 5)

print(o)

Output a matrix (numpy array) of dimension 2-by-3 with each and every value equal to 5

In [ ]:
o = np.full((2, 3), 5)

print(o)

#or#

a = np.ones((2, 3))

o = 5*a

print(o)
 

Output an array by repeating a smaller array of 2 dimensions, 10 times

In [ ]:
a = np.array([[1,2,3],
              [4,5,6]])

o = np.tile(a, 10)

print(o)

Output a 5-by-5 array of random integers between 0 (inclusive) and 10 (exclusive)

In [ ]:
np.random.seed(123) # setting the seed

o = np.random.randint(0, 10, size = (5,5))

print(o)

Output a 3-by-3 array of random numbers following normal distribution

In [ ]:
np.random.seed(123) # setting the seed

o = np.random.normal(size = (3,3))

print(o)

Given 2 numpy arrays as matrices, output the result of multiplying the 2 matrices (as a numpy array)

In [ ]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b = np.array([[2,3,4],
              [5,6,7],
              [8,9,10]])

o = a@b

print(o)

#OR#
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b = np.array([[2,3,4],
              [5,6,7],
              [8,9,10]])

o = np.matmul(a, b)

print(o)

Output the transpose of a matrix (as numpy array)

In [ ]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

a_transpose = a.T

print(a_transpose)
 

How to create a null vector of size 15?

In [ ]:
np.zeros(15)

How to find memory size of any array?

In [16]:
#Create an array
X = np.zeros(15)
# Use size and itemsize function, which returns memory size in bytes
X.size * X.itemsize

120

 How to create vector with values ranging from 20 to 60?

In [ ]:
np.arange(20,61)

How to reverse a vector in numpy?

In [ ]:
X = np.arange(20)
X[::-1]

How to create 4X4 with values from 0 to 15?

In [ ]:
#Make a vector
X = np.arange(16)

#Use reshape function to accomplish this
X.reshape(4,4)

#Or do it one line of code
np.arange(16).reshape(4,4)

How to create 3X3X3 array with random values?

In [27]:
np.random.random((3,3,3))

array([[[0.19422296, 0.57245696, 0.09571252],
        [0.88532683, 0.62724897, 0.72341636],
        [0.01612921, 0.59443188, 0.55678519]],

       [[0.15895964, 0.15307052, 0.69552953],
        [0.31876643, 0.6919703 , 0.55438325],
        [0.38895057, 0.92513249, 0.84167   ]],

       [[0.35739757, 0.04359146, 0.30476807],
        [0.39818568, 0.70495883, 0.99535848],
        [0.35591487, 0.76254781, 0.59317692]]])

How to append arrays in numpy?


In [29]:
import numpy as np

X = np.array([1, 2, 3])
# Use numpy inbuilt append function to append another array
x = np.append(X, [4, 5, 6])

print(x)


[1 2 3 4 5 6]


How to add arrays in numpy?

In [ ]:
#Create an array
X = np.array([1,2,3])
# Use numpy inbuilt add function
np.add(X,[4,5,6])

How to add subtract arrays in numpy?

In [30]:
#Create an array
X = np.array([1,2,3])
# Use numpy inbuilt subtract function
np.subtract(X,[4,5,6])

array([-3, -3, -3])

How to multiply arrays in numpy?

In [ ]:
#Create an array
X = np.array([1,2,3])
# Use numpy inbuilt multiple function
np.multiply(X,X)

divide the following array ([4,8,12,36])

How to inverse matrix in numpy?

In [ ]:
X = np.array([1,2,3,4,5,6,7,8,9,0])
X[::-1]

How to use repeat function in numpy?

In [45]:
np.repeat(6,4)

array([6, 6, 6, 6])

How to sort arrays in numpy?

In [ ]:
X = np.array([1,2,3,100,5,6,-1,8,9,0])
np.sort(X)

 How to use numpy resize function?

In [ ]:
X = np.arange(6).reshape(2,3)

array=([[0, 1, 2],
       [3, 4, 5]])
#use inbuilt resize function
np.resize(X,(3,2))

How to use numpy resize function?

In [ ]:
X = np.arange(6).reshape(2,3)

array=([[0, 1, 2],
       [3, 4, 5]])
#use inbuilt resize function
np.resize(X,(3,2))

 How to use argmax function in numpy?

In [47]:
#solve this error
X = np.arange(6).reshape(2,3)
X
array([[0, 1, 2],
       [3, 4, 5]])
# Use inbuilt argmax function
X.argmax()

TypeError: 'list' object is not callable

Activity.
1)Multiply two NumPy arrays as matrices.
2)Calculate the dot product of two NumPy arrays.
3)Perform element-wise subtraction of two NumPy arrays.